Aprobacion-de-Credito-Bancario-master/WebAplicacionCredito/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAplicacionCredito.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ModeloDB.ModeloDB db;
        public ClientesController(ModeloDB.ModeloDB db)
        {

            this.db = db;
        }
        public IActionResult Index()
        {

            IEnumerable<Cliente> listaCliente = db.cliente.Include(cliente=>cliente.Garante);
            return View(listaCliente);
        }
        //Crear una formulario vacio
        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Garantes
            var listaGarantes = db.garante
                .Select(garante => new
                {
                    GaranteId = garante.GaranteId,
                    Nombres = garante.NombreGarante, 
                    Apellidos = garante.ApellidoGarante
                }).ToList();
            

            // Prepara las listas
            var selectListaGarantes = new SelectList(listaGarantes, "GaranteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListGarantes = selectListaGarantes;
            return View();
        }
        //Grabar un cliente
        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            db.cliente.Add(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El cliente {cliente.NombreCliente + " " + cliente.ApellidoCliente} ha sido creado exitosamente";

            return RedirectToAction("Index");
        }

        //Crear una formulario vacio
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cliente cliente = db.cliente.Find(id);
            return View(cliente);
        }
        //Actualizar una materia
        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            db.cliente.Update(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El cliente {cliente.NombreCliente + " " + cliente.ApellidoCliente} ha sido actualizada exitosamente";


            return RedirectToAction("Index");
        }

        //Enviar a un formulario con los datos de la materia eliminar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Cliente cliente = db.cliente.Include(cliente => cliente.Garante)
                                            .Single(cliente => cliente.ClienteId == id);
            return View(cliente);
        }
        //Actualizar una materia
        [HttpPost]
        public IActionResult Delete(Cliente cliente)
        {
            db.cliente.Remove(cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El cliente ha sido eliminado exitosamente";

            return RedirectToAction("Index");
        }

    }
}

Aprobacion-de-Credito-Bancario-master/WebAplicacionCredito/Controllers/CostoCuotaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo;
using Modelo.Calculo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAplicacionCredito.Controllers
{
    public class CostoCuotaController : Controller
    {
        private readonly ModeloDB.ModeloDB db;
        public CostoCuotaController(ModeloDB.ModeloDB db)
        {

            this.db = db;
        }
        public IActionResult Index()
        {

            IEnumerable<Costo_Cuota> listaCostoCuota = db.costo_cuota
                                          .Include(costo_cuota => costo_cuota.Cliente)
                                          .Include(costo_cuota => costo_cuota.VigenciaTasaAnual);

           
            CalCostoCuota calCostoCuota = new CalCostoCuota(listaCostoCuota);
            ViewBag.CalCostoCuota = calCostoCuota;

            return View(listaCostoCuota);

        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Clientes
            var listaClientes = db.cliente
                .Select(cliente => new
                {
                    ClienteId = cliente.ClienteId,
                    Nombres = cliente.NombreCliente,
                    Apellidos = cliente.ApellidoCliente
                }).ToList();


            // Prepara las listas
            var selectListaClientes = new SelectList(listaClientes, "ClienteId", "Nombres", "Apellidos");

            var listaVigencia = db.vigencia
                .Select(vigencia => new
                {
                    VigenciaId = vigencia.VigenciaTasaAnualId,
                    TasaAnual = vigencia.tasa_anual
                }).ToList();


            // Prepara las listas
            var selectListaVigencia = new SelectList(listaVigencia, "VigenciaId", "TasaAnual");

            // Ingreso a ViewBag
            ViewBag.selectListVigencia = selectListaVigencia;
            ViewBag.selectListClientes = selectListaClientes;
            return View();
        }
        //Grabar un cliente
        [HttpPost]
        public IActionResult Create(Costo_Cuota costo_cuota)
        {
          
            db.costo_cuota.Add(costo_cuota);
            db.SaveChanges();

            TempData["mensaje"] = $"La cuota {costo_cuota.Costo_CuotaId} ha sido creada exitosamente";

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Costo_Cuota costo_cuota = db.costo_cuota.Find(id);
            return View(costo_cuota);
        }
        //Actualizar una materia
        [HttpPost]
        public IActionResult Edit(Costo_Cuota costo_cuota)
        {
            db.costo_cuota.Update(costo_cuota);
            db.SaveChanges();

            TempData["mensaje"] = $"La cuota  {costo_cuota.Costo_CuotaId} ha sido actualizada exitosamente";


            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Costo_Cuota costo_cuota = db.costo_cuota.Include(costo_cuota => costo_cuota.Cliente)
                                            .Single(costo_cuota => costo_cuota.Costo_CuotaId == id);
            return View(costo_cuota);
        }
        //Actualizar una materia
        [HttpPost]
        public IActionResult Delete(Costo_Cuota costo_cuota)
        {
            db.costo_cuota.Remove(costo_cuota);
            db.SaveChanges();

            TempData["mensaje"] = $"La cuota ha sido eliminada exitosamente";

            return RedirectToAction("Index");
        }
    }
}

Aprobacion-de-Credito-Bancario-master/WebAplicacionCredito/Controllers/HistorialClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo;
using Modelo.Calculo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAplicacionCredito.Controllers
{
    public class HistorialClienteController : Controller
    {
        private readonly ModeloDB.ModeloDB db;
        public HistorialClienteController(ModeloDB.ModeloDB db)
        {

            this.db = db;
        }
        public IActionResult Index(int id)
        {

            IEnumerable<Historial_Cliente> listaHistorialCliente = db.historial_cliente.Include(historial_cliente => historial_cliente.Cliente);
            return View(listaHistorialCliente);
        }
        //Crear una formulario vacio
        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Validaciones
            var listaValidaciones = db.validaciones
                .Select(validaciones => new
                {
                    ValidacionesId = validaciones.ValidacionesId,
                    ValidacionHistorialCliente = validaciones.val_historial_cliente
                    
                }).ToList();


            // Prepara las listas
            var selectListaValidaciones = new SelectList(listaValidaciones, "ValidacionesId", "ValidacionHistorialCliente");

            // Ingreso a ViewBag
            ViewBag.selectListValidaciones = selectListaValidaciones;
           
            return View();
        }
        [HttpPost]

        public IActionResult Create(Historial_Cliente historial_cliente)
        {
            db.historial_cliente.Add(historial_cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El registro del cliente {historial_cliente.Cliente.NombreCliente + " " + historial_cliente.Cliente.ApellidoCliente} ha sido creado exitosamente";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Historial_Cliente historial_cliente = db.historial_cliente.Find(id);
            return View(historial_cliente);
           
        }
        [HttpPost]
        public IActionResult Edit(Historial_Cliente historial_cliente)
        {
            db.historial_cliente.Update(historial_cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El registro del cliente {historial_cliente.Cliente.NombreCliente + " " + historial_cliente.Cliente.ApellidoCliente} ha sido actualizada exitosamente";


            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Historial_Cliente historial_cliente = db.historial_cliente.Find(id);
            return View(historial_cliente);
        }
        //Actualizar una materia
        [HttpPost]
        public IActionResult Delete(Historial_Cliente historial_cliente)
        {
            db.historial_cliente.Remove(historial_cliente);
            db.SaveChanges();

            TempData["mensaje"] = $"El registro ha sido eliminado exitosamente";

            return RedirectToAction("Index");
        }

     
        public IActionResult Validar(int id)
        {
            var historial_cliente = db.historial_cliente
               .Include(historial_cliente => historial_cliente.Cliente)
               .Include(historial_cliente => historial_cliente.Validaciones)
                 .ThenInclude(validaciones => validaciones.Cliente)
               .Include(historial_cliente => historial_cliente.Validaciones)
                  .ThenInclude(validaciones => validaciones.Historial_Cliente)
                  .ThenInclude(validaciones => validaciones.Cliente)
           .Single(historial_cliente => historial_cliente.Historial_ClienteId == id);

            // .Single(cliente => cliente.ClienteId == id);
            var cliente = db.cliente.Single(cliente => cliente.ClienteId == historial_cliente.Cliente.ClienteId);

            CalHistorialCliente calHistorialCliente = new CalHistorialCliente(cliente);
            ViewBag.CalHistorialCliente = calHistorialCliente;
            return View(historial_cliente);
        }
    }
}

Aprobacion-de-Credito-Bancario-master/WebAplicacionCredito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAplicacionCredito</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAplicacionCredito</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistorialCliente" asp-action="Index">Historial Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Garante" asp-action="Index">Garantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CostoCuota" asp-action="Index">Cuotas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAplicacionCredito - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>